name: test

on:
  push:
    branches: [master]
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: mlugg/setup-zig@v1
      with: 
        version: "0.13.0"
    - run: zig build test
